datasource:
  driver-class-name: "com.mysql.jdbc.Driver"
  url: "jdbc:mysql://52.79.133.27:3306/yhdb?useUnicode=true&characterEncoding=utf-8"
  user-name: "hyeyoon"
  password: "admin123"
  initial-size: 10
  max-active: 10
  max-idle: 10
  min-idle: 10
  max-wait: 3000